campsitemanager/users/urls.py
from django.urls import path

from campsitemanager.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from campsitemanager.users.views import camping_population_chart_view
from campsitemanager.users.views import current_occupancy_view
from campsitemanager.users.views import create_reservation_view
from campsitemanager.users.views import reservation_success_view
from campsitemanager.users.views import my_reservations_view
from campsitemanager.users.views import reservation_detail_view
from campsitemanager.users.views import cancel_reservation_view
from campsitemanager.users.views import reservation_pdf_view

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("campsitemanager.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path('populacja/', camping_population_chart_view, name='populacja'),
    path('obecne-oblozenie/', current_occupancy_view, name='obecne_oblozenie'),
    path('rezerwuj/', create_reservation_view, name='create_reservation'),
    path('rezerwacja-sukces/', reservation_success_view, name='reservation_success'),
    path('moje-rezerwacje/', my_reservations_view, name='my_reservations'),
    path('rezerwacja/<int:id>/', reservation_detail_view, name='reservation_detail'),
    path('rezerwacja/<int:id>/pdf/', reservation_pdf_view, name='reservation_pdf'),
    path('rezerwacja/<int:id>/cancel/', cancel_reservation_view, name='cancel_reservation'),
    path('i18n/', include('django.conf.urls.i18n')),  # Add this
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

campsitemanager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models  # Ensure this line is at the top of your file
from campsitemanager.users.managers import UserManager

class User(AbstractUser):
    """
    Default custom user model for campsitemanager.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})


class ReservationInquiry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="reservations")
    # Basic information
    full_name = models.CharField(max_length=255, verbose_name=_("Imię i nazwisko"))
    email = models.EmailField(verbose_name=_("Email"))
    phone_number = models.CharField(max_length=15, verbose_name=_("Numer telefonu"))

    # Reservation details
    start_date = models.DateField(verbose_name=_("Data rozpoczęcia"))
    end_date = models.DateField(verbose_name=_("Data zakończenia"))

    # Guests
    num_adults = models.PositiveIntegerField(verbose_name=_("Liczba dorosłych"))
    num_children_0_3 = models.PositiveIntegerField(default=0, verbose_name=_("Liczba dzieci (0-3 lata)"))
    num_children_4_13 = models.PositiveIntegerField(default=0, verbose_name=_("Liczba dzieci (4-13 lat)"))
    num_animals = models.PositiveIntegerField(default=0, verbose_name=_("Liczba zwierząt"))

    # Accommodation
    TENT_CHOICES = [
        ('2p', _('Namiot 2-osobowy')),
        ('3-4p', _('Namiot 3-4 osobowy')),
        ('5-6p', _('Namiot 5-6 osobowy')),
    ]
    tent_type = models.CharField(max_length=5, choices=TENT_CHOICES, blank=True, null=True, verbose_name=_("Rodzaj namiotu"))

    caravan_required = models.BooleanField(default=False, verbose_name=_("Czy wymagana przyczepa/kamper"))

    # Additional options
    electricity_for_tent = models.BooleanField(default=False, verbose_name=_("Prąd i sanitariaty dla namiotu"))
    electricity_for_caravan = models.BooleanField(default=False, verbose_name=_("Prąd i sanitariaty dla przyczepy/kampera"))
    extra_person_count = models.PositiveIntegerField(default=0, verbose_name=_("Liczba dodatkowych osób"))
    waste_disposal = models.BooleanField(default=False, verbose_name=_("Wywóz odpadów"))
    parking_required = models.BooleanField(default=False, verbose_name=_("Parking wymagany"))

    # Beach stay
    num_beach_stay_adults = models.PositiveIntegerField(default=0, verbose_name=_("Liczba dorosłych na plaży"))
    num_beach_stay_children = models.PositiveIntegerField(default=0, verbose_name=_("Liczba dzieci na plaży"))

    # Discount for longer stay
    apply_discount = models.BooleanField(default=False, verbose_name=_("Zastosuj zniżkę za pobyt powyżej 5 dni"))

    # Inquiry creation timestamp
    inquiry_date = models.DateTimeField(auto_now_add=True, verbose_name=_("Data zapytania"))

    # Status fields
    is_confirmed = models.BooleanField(default=False, help_text=_("Czy pobyt został potwierdzony przez camping?"), verbose_name=_("Potwierdzone"))
    is_canceled = models.BooleanField(default=False, help_text=_("Czy rezerwacja została anulowana przez użytkownika?"), verbose_name=_("Anulowane"))

    # Method to calculate the length of stay
    @property
    def length_of_stay(self):
        return (self.end_date - self.start_date).days

    def __str__(self):
        return f"{self.full_name} - {self.start_date} to {self.end_date}"

    # Example method to calculate the total cost (optional and customizable)
    def calculate_total_cost(self):
        # Placeholder: You would implement the logic to calculate total cost based on options selected.
        pass

    class Meta:
        verbose_name = _("Rezerwacja")
        verbose_name_plural = _("Rezerwacje")

campsitemanager/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView


from django.shortcuts import render, redirect
from django.utils import timezone
from datetime import timedelta
# from .models import ReservationInquiry

from campsitemanager.users.models import ReservationInquiry
from campsitemanager.users.forms import ReservationInquiryForm

from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from django.utils.translation import gettext as _
from django.conf import settings
from django.contrib.staticfiles import finders
import qrcode
import os
from io import BytesIO

from django.contrib import messages
from django.contrib.auth.decorators import login_required
User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()



def get_camping_population_data():
    today = timezone.now().date()
    population_data = []

    for i in range(30):
        current_date = today + timedelta(days=i)
        reservations = ReservationInquiry.objects.filter(
            start_date__lte=current_date,
            end_date__gte=current_date,
            is_confirmed=True,
            is_canceled=False
        )
        
        total_people = sum(
            reservation.num_adults + 
            reservation.num_children_0_3 + 
            reservation.num_children_4_13 + 
            reservation.extra_person_count 
            for reservation in reservations
        )
        
        population_data.append({
            'date': current_date,
            'total_people': total_people
        })

    return population_data

def camping_population_chart_view(request):
    population_data = get_camping_population_data()
    context = {
        'population_data': population_data
    }
    return render(request, 'pages/camping_population_chart.html', context)



def get_current_occupancy():
    today = timezone.now().date()
    reservations = ReservationInquiry.objects.filter(
        start_date__lte=today,
        end_date__gte=today,
        is_confirmed=True,
        is_canceled=False
    )

    # Example thresholds, adjust these based on your camping's capacity
    low_threshold = 40
    high_threshold = 80

    total_people = sum(
        reservation.num_adults + 
        reservation.num_children_0_3 + 
        reservation.num_children_4_13 + 
        reservation.extra_person_count 
        for reservation in reservations
    )

    if total_people <= low_threshold:
        occupancy_level = 'low'
    elif total_people > high_threshold:
        occupancy_level = 'high'
    else:
        occupancy_level = 'medium'

    return total_people, occupancy_level

def current_occupancy_view(request):
    total_people, occupancy_level = get_current_occupancy()
    context = {
        'total_people': total_people,
        'occupancy_level': occupancy_level,
        'today': timezone.now(),  # Dodanie dzisiejszej daty do kontekstu
    }
    return render(request, 'pages/current_occupancy_chart.html', context)

# @login_required
def create_reservation_view(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            # Redirect to login page if the user is not authenticated
            return redirect(f"{reverse('account_login')}?next={request.path}")
        form = ReservationInquiryForm(request.POST)
        if form.is_valid():
            print('form valid!')
            # Create a ReservationInquiry object from form data
            reservation = ReservationInquiry(
                user=request.user,
                full_name=form.cleaned_data['full_name'],
                email=form.cleaned_data['email'],
                phone_number=form.cleaned_data['phone_number'],
                start_date=form.cleaned_data['start_date'],
                end_date=form.cleaned_data['end_date'],
                num_adults=form.cleaned_data['num_adults'],
                num_children_0_3=form.cleaned_data['num_children_0_3'],
                num_children_4_13=form.cleaned_data['num_children_4_13'],
                num_animals=form.cleaned_data.get('num_animals', 0),  # Optional field
                tent_type=form.cleaned_data.get('tent_type', None),
                caravan_required=form.cleaned_data.get('caravan_required', False),
                electricity_for_tent=form.cleaned_data.get('electricity_for_tent', False),
                electricity_for_caravan=form.cleaned_data.get('electricity_for_caravan', False),
                extra_person_count=form.cleaned_data.get('extra_person_count', 0),
                waste_disposal=form.cleaned_data.get('waste_disposal', False),
                parking_required=form.cleaned_data.get('parking_required', False),
                # num_beach_stay_adults=form.cleaned_data.get('num_beach_stay_adults', 0),
                # num_beach_stay_children=form.cleaned_data.get('num_beach_stay_children', 0),
                apply_discount=form.cleaned_data.get('apply_discount', False),
                is_confirmed=False  # Initially not confirmed
            )
            # Save the reservation
            reservation.save()

            # Redirect to the success page after saving the reservation
            return redirect(reverse('reservation_success'))
        else:
            print(form.errors)

    else:
        form = ReservationInquiryForm()

    return render(request, 'pages/create_reservation.html', {'form': form})


def reservation_success_view(request):
    return render(request, 'pages/reservation_success.html')



@login_required
def my_reservations_view(request):
    user_reservations = ReservationInquiry.objects.filter(user=request.user).order_by('-start_date')

    # Add a calculated field for total children in each reservation
    for reservation in user_reservations:
        reservation.total_children = reservation.num_children_0_3 + reservation.num_children_4_13

    context = {
        'reservations': user_reservations,
    }
    return render(request, 'pages/my_reservations.html', context)

def reservation_detail_view(request, id):
    reservation = ReservationInquiry.objects.get(id=id, user=request.user)
    context = {
        'reservation': reservation,
    }
    return render(request, 'pages/reservation_detail.html', context)


@login_required
def cancel_reservation_view(request, id):
    reservation = ReservationInquiry.objects.get(id=id, user=request.user)

    if request.method == 'POST':
        reservation.is_canceled = True
        reservation.save()
        messages.success(request, 'Your reservation has been canceled.')
        return redirect('my_reservations')

    context = {
        'reservation': reservation,
    }
    return render(request, 'pages/cancel_reservation_confirm.html', context)


def dashboard_callback(request, context):
    # You can modify the context here if needed
    return context



def reservation_pdf_view(request, id):
    reservation = ReservationInquiry.objects.get(id=id, user=request.user)

    # Ścieżka do logo Kemping z folderu statycznego
    logo_path = finders.find('images/kemping_logo.png')

    # Przygotuj odpowiedź HTTP z odpowiednim typem treści
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="reservation_{reservation.id}.pdf"'

    # Ścieżka do fontu DejaVu Sans obsługującego polskie znaki
    font_path = finders.find('fonts/DejaVuSans.ttf')

    # Sprawdzenie, czy plik fontu został znaleziony
    if font_path:
        # Rejestracja nowego fontu w reportlab
        pdfmetrics.registerFont(TTFont('DejaVu', font_path))
        font_name = 'DejaVu'
    else:
        # Jeśli font nie zostanie znaleziony, użyj domyślnego fontu
        font_name = 'Helvetica'


    # Ustawienia dla formatu A4
    p = canvas.Canvas(response, pagesize=A4)
    width, height = A4
    p.setTitle(f"Reservation_{reservation.id}")
    
    # Dodaj logo Kemping, jeśli plik istnieje
    if logo_path:
        logo = ImageReader(logo_path)
        p.drawImage(logo, 40, height - 100, width=120, height=50, mask='auto')
    

    # Dodaj mały tekst pod logo
    p.setFont(font_name, 10)  # Ustawiamy mniejszy rozmiar czcionki
    p.drawString(40, height - 120, _("Wydrukuj tę stronę i okaż ją przy wjeździe na kemping"))

    # Dodaj nagłówek
    p.setFont(font_name, 16)
    p.drawString(40, height - 150, _("Reservation Details"))
    
    # Separator
    p.setStrokeColor(colors.grey)
    p.setLineWidth(1)
    p.line(40, height - 160, width - 40, height - 160)

    # Zmienne do trzymania pozycji tekstu
    y_position = height - 180
    line_spacing = 20

    # Stylizowane pola rezerwacji
    p.setFont(font_name, 12)
    
    def draw_field(label, value):
        nonlocal y_position

campsitemanager/templates/pages/about.html
{% extends "base.html" %}

{% block content %}
    <!-- Hero Section -->
    <section class="bg-cover bg-center h-96" style="background-image: url('/static/images/camping_lake.jpg');">
        <div class="bg-black bg-opacity-60 h-full flex flex-col justify-center items-center text-center text-white">
            <h1 class="text-5xl font-bold mb-4">O nas - Kemping Dąbrówno</h1>
            <p class="text-xl mb-4">Twoje miejsce na relaks, przygodę i niezapomniane wspomnienia</p>
        </div>
    </section>

    <!-- Welcome Section -->
    <section class="py-16 bg-gray-100 text-center">
        <div class="container mx-auto px-4">
            <h2 class="text-4xl font-bold mb-8">Witamy na Kempingu Dąbrówno</h2>
            <p class="text-lg mb-6">Położony nad spokojnym jeziorem, Kemping Dąbrówno oferuje idealne połączenie natury, komfortu i zabawy. Niezależnie od tego, czy szukasz relaksu, czy przygody, nasz kemping to doskonałe miejsce dla rodzin, par i przyjaciół. Od ognisk i muzyki na żywo po świeże, pyszne jedzenie i zapierające dech w piersiach zachody słońca – Twoje doświadczenie kempingowe będzie niezapomniane.</p>
        </div>
    </section>

    <!-- Nature and Relaxation Section -->
    <section class="py-16">
        <div class="container mx-auto px-4">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                <div>
                    <h3 class="text-3xl font-semibold mb-4">Relaksujący Wypoczynek na Łonie Natury</h3>
                    <p class="text-lg mb-4">Kemping Dąbrówno to miejsce pełne pięknych widoków na jezioro i spokojnych otoczeń. Niezależnie od tego, czy podziwiasz złocisty zachód słońca na naszej piaszczystej plaży, czy spacerujesz pośród zieleni, nasz kemping zapewnia spokojny i regenerujący odpoczynek z dala od zgiełku codziennego życia.</p>
                </div>
                <div>
                    <img src="/static/images/nature_relax.jpg" alt="Relaks na łonie natury" class="rounded-lg shadow-md">
                </div>
            </div>
        </div>
    </section>

    <!-- High-Quality Infrastructure Section -->
    <section class="py-16 bg-gray-100">
        <div class="container mx-auto px-4">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
                <div>
                    <img src="/static/images/infrastructure.jpg" alt="Nowoczesna infrastruktura" class="rounded-lg shadow-md">
                </div>
                <div>
                    <h3 class="text-3xl font-semibold mb-4">Wysokiej Jakości Infrastruktura</h3>
                    <p class="text-lg mb-4">Na Kempingu Dąbrówno dbamy o komfort naszych gości. Czyste, nowoczesne toalety i prysznice, przestronne miejsca kempingowe oraz wygodne miejsca do siedzenia sprawią, że Twój pobyt będzie przyjemny i bezproblemowy. Oferujemy również wypożyczalnię rowerów i kajaków, dzięki czemu zawsze jest coś ciekawego do zrobienia.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Fun for Everyone Section -->
    <section class="py-16">
        <div class="container mx-auto px-4 text-center">
            <h3 class="text-4xl font-semibold mb-8">Zabawa dla Każdego</h3>
            <p class="text-lg mb-6">Na Kempingu Dąbrówno każdy znajdzie coś dla siebie. Miłośnicy wody mogą odkrywać jezioro na rowerach wodnych, kajakach lub deskach SUP, a dzieci mogą korzystać z placu zabaw i boiska do siatkówki. Wieczorne ogniska, muzyka na żywo i sety DJ-skie tworzą przyjazną i integrującą atmosferę, sprzyjającą nawiązywaniu nowych znajomości i relaksowi.</p>
            <img src="/static/images/fun_for_everyone.jpg" alt="Zabawa dla każdego" class="mx-auto rounded-lg shadow-md">
        </div>
    </section>

    <!-- Friendly Staff Section -->
    <section class="py-16 bg-gray-100">
        <div class="container mx-auto px-4">
            <h3 class="text-4xl font-semibold text-center mb-8">Przyjazna i Pomocna Obsługa</h3>
            <p class="text-lg text-center mb-6">Nasi goście niezmiennie chwalą serdeczność i życzliwość naszej obsługi. Od momentu przyjazdu, powitamy Cię z uśmiechem. Niezależnie od tego, czy potrzebujesz pomocy przy wypożyczeniu sprzętu, czy rekomendacji co do lokalnych atrakcji, nasz zespół jest zawsze gotowy, aby pomóc. Dbamy o to, aby każde doświadczenie naszych gości było pozytywne i niezapomniane.</p>
        </div>
    </section>

    <!-- Delicious Food Section -->
    <section class="py-16">
        <div class="container mx-auto px-4 text-center">
            <h3 class="text-4xl font-semibold mb-8">Pyszne Jedzenie i Doskonała Gościnność</h3>
            <p class="text-lg mb-6">Rozkoszuj się smakołykami w naszym barze, gdzie serwujemy świeżo wędzoną rybę, kebaby i przepyszne desery, takie jak domowa szarlotka z lodami. Nasza oferta kulinarna jest równie różnorodna, co dostępne atrakcje, co sprawia, że każdy posiłek to przyjemność.</p>
            <img src="/static/images/food.jpg" alt="Pyszne jedzenie" class="mx-auto rounded-lg shadow-md">
        </div>
    </section>

    <!-- Events Section -->
    <section class="py-16 bg-gray-100">
        <div class="container mx-auto px-4">
            <h3 class="text-4xl font-semibold text-center mb-8">Weekendowe Wydarzenia i Muzyka na Żywo</h3>
            <p class="text-lg text-center mb-6">Dla tych, którzy kochają zabawę i rozrywkę, organizujemy weekendowe wydarzenia z udziałem zespołów na żywo, DJ-ów i atrakcji kulturalnych. Każdego wieczoru goście gromadzą się przy naszym dużym ognisku, dzieląc się historiami i ciesząc się swobodną atmosferą. Te wydarzenia tworzą wspomnienia, które sprawiają, że goście wracają do nas rok po roku.</p>
        </div>
    </section>

    <!-- Why Choose Us Section -->
    <section class="py-16">
        <div class="container mx-auto px-4 text-center">
            <h3 class="text-4xl font-semibold mb-8">Dlaczego Wybrać Kemping Dąbrówno?</h3>
            <ul class="list-disc list-inside text-lg text-left inline-block">
                <li class="mb-2"><strong>Piękne położenie w naturze</strong>, z dostępem do jeziora i zapierającymi dech w piersiach zachodami słońca</li>
                <li class="mb-2"><strong>Czyste i nowoczesne udogodnienia</strong>, w tym toalety i prysznice z ciepłą wodą</li>
                <li class="mb-2"><strong>Zabawa i przygoda</strong>, od sportów wodnych po wieczorne ogniska</li>
                <li class="mb-2"><strong>Przyjazna i pomocna obsługa</strong>, która dba o Twój komfort</li>
                <li><strong>Pyszne jedzenie</strong> i żywe wydarzenia towarzyskie co weekend</li>
            </ul>
        </div>
    </section>
{% endblock %}

campsitemanager/templates/pages/cancel_reservation_confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="container mx-auto mt-4">
    <h1 class="text-2xl font-semibold mb-4">{% trans "Cancel Reservation" %}</h1>
    <p>{% trans "Are you sure you want to cancel your reservation for" %} {{ reservation.start_date }} {% trans "to" %} {{ reservation.end_date }}?</p>
    
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
            {% trans "Yes, Cancel Reservation" %}
        </button>
        <a href="{% url 'my_reservations' %}" class="text-blue-500 ml-4">{% trans "No, go back" %}</a>
    </form>
</div>
{% endblock %}

campsitemanager/templates/pages/new_inquiry.html
{% extends "base.html" %}

campsitemanager/templates/pages/reservation_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="container mx-auto mt-4">
    <h1 class="text-2xl font-semibold mb-4">{% trans "Reservation Details" %}</h1>
    <div class="mt-4">
        <a href="{% url 'reservation_pdf' reservation.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
           Pobierz karte meldunkową 
        </a>
    </div>
    
    <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <h2 class="text-xl font-semibold mb-4">{{ reservation.full_name }}</h2>
        <p><strong>{% trans "Reservation ID:" %}</strong> {{ reservation.id }}</p>
        <p><strong>{% trans "Start Date:" %}</strong> {{ reservation.start_date }}</p>
        <p><strong>{% trans "End Date:" %}</strong> {{ reservation.end_date }}</p>
        <p><strong>{% trans "Number of Adults:" %}</strong> {{ reservation.num_adults }}</p>
        <p><strong>{% trans "Number of Children (0-3 years):" %}</strong> {{ reservation.num_children_0_3 }}</p>
        <p><strong>{% trans "Number of Children (4-13 years):" %}</strong> {{ reservation.num_children_4_13 }}</p>
        <p><strong>{% trans "Number of Animals:" %}</strong> {{ reservation.num_animals }}</p>
        <p><strong>{% trans "Tent Type:" %}</strong> 
            {% if reservation.tent_type %}
                {{ reservation.get_tent_type_display }}
            {% else %}
                {% trans "No tent required" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Caravan Required:" %}</strong> 
            {% if reservation.caravan_required %}
                {% trans "Yes" %}
            {% else %}
                {% trans "No" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Electricity for Tent:" %}</strong> 
            {% if reservation.electricity_for_tent %}
                {% trans "Yes" %}
            {% else %}
                {% trans "No" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Electricity for Caravan:" %}</strong> 
            {% if reservation.electricity_for_caravan %}
                {% trans "Yes" %}
            {% else %}
                {% trans "No" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Extra Person Count:" %}</strong> {{ reservation.extra_person_count }}</p>
        <p><strong>{% trans "Waste Disposal:" %}</strong> 
            {% if reservation.waste_disposal %}
                {% trans "Yes" %}
            {% else %}
                {% trans "No" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Parking Required:" %}</strong> 
            {% if reservation.parking_required %}
                {% trans "Yes" %}
            {% else %}
                {% trans "No" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Number of Adults at Beach:" %}</strong> {{ reservation.num_beach_stay_adults }}</p>
        <p><strong>{% trans "Number of Children at Beach:" %}</strong> {{ reservation.num_beach_stay_children }}</p>
        <p><strong>{% trans "Discount Applied:" %}</strong> 
            {% if reservation.apply_discount %}
                {% trans "Yes" %}
            {% else %}
                {% trans "No" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Reservation Status:" %}</strong> 
            {% if reservation.is_confirmed %}
                {% trans "Confirmed" %}
            {% else %}
                {% trans "Pending" %}
            {% endif %}
        </p>
        <p><strong>{% trans "Cancellation Status:" %}</strong> 
            {% if reservation.is_canceled %}
                {% trans "Canceled" %}
            {% else %}
                {% trans "Active" %}
            {% endif %}
        </p>
    </div>

    <a href="{% url 'my_reservations' %}" class="text-blue-500">{% trans "Back to My Reservations" %}</a>
</div>
{% endblock %}